// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/features/auth/apply/data/data_source/auth/apply_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;
import 'dart:io' as _i25;

import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i7;
import 'package:shared_preferences/shared_preferences.dart' as _i14;
import 'package:tracking_app/core/api_layer/api_client/api_client.dart' as _i15;
import 'package:tracking_app/core/api_layer/models/request/change_password_request_body.dart'
    as _i27;
import 'package:tracking_app/core/api_layer/models/request/update_profile_request_dto.dart'
    as _i26;
import 'package:tracking_app/core/api_layer/models/request/update_vehical_request_dto.dart'
    as _i28;
import 'package:tracking_app/core/api_layer/models/response/auth/apply_response.dart'
    as _i8;
import 'package:tracking_app/core/api_layer/models/response/profile/all_vehical_response.dart'
    as _i13;
import 'package:tracking_app/core/api_layer/models/response/profile/change_password_response_dto.dart'
    as _i12;
import 'package:tracking_app/core/api_layer/models/response/profile/get_logged_driver.dart'
    as _i9;
import 'package:tracking_app/core/api_layer/models/response/profile/update_photo_response_dto.dart'
    as _i11;
import 'package:tracking_app/core/api_layer/models/response/profile/update_profile_response_dto.dart'
    as _i10;
import 'package:tracking_app/core/modules/shared_preferences_module.dart'
    as _i29;
import 'package:tracking_app/features/auth/forget_password/data/models/request/forget_password_request_dto.dart'
    as _i17;
import 'package:tracking_app/features/auth/forget_password/data/models/request/reset_password_request_dto.dart'
    as _i19;
import 'package:tracking_app/features/auth/forget_password/data/models/request/verify_reset_code_request_dto.dart'
    as _i18;
import 'package:tracking_app/features/auth/forget_password/data/models/response/forget_password_response_dto.dart'
    as _i2;
import 'package:tracking_app/features/auth/forget_password/data/models/response/reset_password_response_dto.dart'
    as _i4;
import 'package:tracking_app/features/auth/forget_password/data/models/response/verify_reset_code_response_dto.dart'
    as _i3;
import 'package:tracking_app/features/auth/login/data/model/login_request_dto.dart'
    as _i24;
import 'package:tracking_app/features/auth/login/data/model/login_response_dto.dart'
    as _i23;
import 'package:tracking_app/features/home/presentation/Tabs/home_tab/data/models/pending_orders_response.dart'
    as _i5;
import 'package:tracking_app/features/order_details/data/models/request/update_order_request.dart'
    as _i22;
import 'package:tracking_app/features/order_details/data/models/response/start_order_model.dart'
    as _i20;
import 'package:tracking_app/features/order_details/data/models/response/update_order_state_response.dart'
    as _i21;
import 'package:tracking_app/features/orders/data/models/my_orders_response.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForgetPasswordResponseDto_0 extends _i1.SmartFake
    implements _i2.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyResetCodeResponseDto_1 extends _i1.SmartFake
    implements _i3.VerifyResetCodeResponseDto {
  _FakeVerifyResetCodeResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseDto_2 extends _i1.SmartFake
    implements _i4.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePendingOrdersResponse_3 extends _i1.SmartFake
    implements _i5.PendingOrdersResponse {
  _FakePendingOrdersResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMyOrdersResponse_4 extends _i1.SmartFake
    implements _i6.MyOrdersResponse {
  _FakeMyOrdersResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpResponse_5<T> extends _i1.SmartFake
    implements _i7.HttpResponse<T> {
  _FakeHttpResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApplyResponse_6 extends _i1.SmartFake implements _i8.ApplyResponse {
  _FakeApplyResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetLoggedDriver_7 extends _i1.SmartFake
    implements _i9.GetLoggedDriver {
  _FakeGetLoggedDriver_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateProfileResponseDto_8 extends _i1.SmartFake
    implements _i10.UpdateProfileResponseDto {
  _FakeUpdateProfileResponseDto_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdatePhotoResponseDto_9 extends _i1.SmartFake
    implements _i11.UpdatePhotoResponseDto {
  _FakeUpdatePhotoResponseDto_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChangePasswordResponseDto_10 extends _i1.SmartFake
    implements _i12.ChangePasswordResponseDto {
  _FakeChangePasswordResponseDto_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAllVehicalResponse_11 extends _i1.SmartFake
    implements _i13.AllVehicalResponse {
  _FakeAllVehicalResponse_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedPreferences_12 extends _i1.SmartFake
    implements _i14.SharedPreferences {
  _FakeSharedPreferences_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i15.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<_i2.ForgetPasswordResponseDto> forgetPassword({
    required _i17.ForgetPasswordRequestDto? forgetPasswordRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [], {
              #forgetPasswordRequestDto: forgetPasswordRequestDto,
            }),
            returnValue: _i16.Future<_i2.ForgetPasswordResponseDto>.value(
              _FakeForgetPasswordResponseDto_0(
                this,
                Invocation.method(#forgetPassword, [], {
                  #forgetPasswordRequestDto: forgetPasswordRequestDto,
                }),
              ),
            ),
          )
          as _i16.Future<_i2.ForgetPasswordResponseDto>);

  @override
  _i16.Future<_i3.VerifyResetCodeResponseDto> verifyResetCode({
    required _i18.VerifyResetCodeRequestDto? verifyResetCodeRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [], {
              #verifyResetCodeRequestDto: verifyResetCodeRequestDto,
            }),
            returnValue: _i16.Future<_i3.VerifyResetCodeResponseDto>.value(
              _FakeVerifyResetCodeResponseDto_1(
                this,
                Invocation.method(#verifyResetCode, [], {
                  #verifyResetCodeRequestDto: verifyResetCodeRequestDto,
                }),
              ),
            ),
          )
          as _i16.Future<_i3.VerifyResetCodeResponseDto>);

  @override
  _i16.Future<_i4.ResetPasswordResponseDto> resetPassword({
    required _i19.ResetPasswordRequestDto? resetPasswordRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #resetPasswordRequestDto: resetPasswordRequestDto,
            }),
            returnValue: _i16.Future<_i4.ResetPasswordResponseDto>.value(
              _FakeResetPasswordResponseDto_2(
                this,
                Invocation.method(#resetPassword, [], {
                  #resetPasswordRequestDto: resetPasswordRequestDto,
                }),
              ),
            ),
          )
          as _i16.Future<_i4.ResetPasswordResponseDto>);

  @override
  _i16.Future<_i5.PendingOrdersResponse> getPendingDriverOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingDriverOrders, []),
            returnValue: _i16.Future<_i5.PendingOrdersResponse>.value(
              _FakePendingOrdersResponse_3(
                this,
                Invocation.method(#getPendingDriverOrders, []),
              ),
            ),
          )
          as _i16.Future<_i5.PendingOrdersResponse>);

  @override
  _i16.Future<_i20.StartOrderModel?> startOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#startOrder, [orderId]),
            returnValue: _i16.Future<_i20.StartOrderModel?>.value(),
          )
          as _i16.Future<_i20.StartOrderModel?>);

  @override
  _i16.Future<_i21.UpdateOrderStateResponse?> updateOrder(
    String? orderId,
    _i22.UpdateOrderRequest? updateOrderRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrder, [orderId, updateOrderRequest]),
            returnValue: _i16.Future<_i21.UpdateOrderStateResponse?>.value(),
          )
          as _i16.Future<_i21.UpdateOrderStateResponse?>);

  @override
  _i16.Future<_i6.MyOrdersResponse> getMyOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getMyOrders, []),
            returnValue: _i16.Future<_i6.MyOrdersResponse>.value(
              _FakeMyOrdersResponse_4(
                this,
                Invocation.method(#getMyOrders, []),
              ),
            ),
          )
          as _i16.Future<_i6.MyOrdersResponse>);

  @override
  _i16.Future<_i7.HttpResponse<_i23.LoginResponseDto>> login({
    required _i24.LoginRequestDto? loginRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#loginRequestDto: loginRequestDto}),
            returnValue:
                _i16.Future<_i7.HttpResponse<_i23.LoginResponseDto>>.value(
                  _FakeHttpResponse_5<_i23.LoginResponseDto>(
                    this,
                    Invocation.method(#login, [], {
                      #loginRequestDto: loginRequestDto,
                    }),
                  ),
                ),
          )
          as _i16.Future<_i7.HttpResponse<_i23.LoginResponseDto>>);

  @override
  _i16.Future<_i8.ApplyResponse> apply(
    String? email,
    String? password,
    String? rePassword,
    String? firstName,
    String? lastName,
    String? phone,
    String? gender,
    String? NID,
    String? vehicleType,
    String? vehicleNumber,
    String? country,
    _i25.File? vehicleLicense,
    _i25.File? NIDImg,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#apply, [
              email,
              password,
              rePassword,
              firstName,
              lastName,
              phone,
              gender,
              NID,
              vehicleType,
              vehicleNumber,
              country,
              vehicleLicense,
              NIDImg,
            ]),
            returnValue: _i16.Future<_i8.ApplyResponse>.value(
              _FakeApplyResponse_6(
                this,
                Invocation.method(#apply, [
                  email,
                  password,
                  rePassword,
                  firstName,
                  lastName,
                  phone,
                  gender,
                  NID,
                  vehicleType,
                  vehicleNumber,
                  country,
                  vehicleLicense,
                  NIDImg,
                ]),
              ),
            ),
          )
          as _i16.Future<_i8.ApplyResponse>);

  @override
  _i16.Future<_i9.GetLoggedDriver> getLoggedUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedUserData, []),
            returnValue: _i16.Future<_i9.GetLoggedDriver>.value(
              _FakeGetLoggedDriver_7(
                this,
                Invocation.method(#getLoggedUserData, []),
              ),
            ),
          )
          as _i16.Future<_i9.GetLoggedDriver>);

  @override
  _i16.Future<_i10.UpdateProfileResponseDto> editProfile(
    _i26.UpdateProfileRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [request]),
            returnValue: _i16.Future<_i10.UpdateProfileResponseDto>.value(
              _FakeUpdateProfileResponseDto_8(
                this,
                Invocation.method(#editProfile, [request]),
              ),
            ),
          )
          as _i16.Future<_i10.UpdateProfileResponseDto>);

  @override
  _i16.Future<_i11.UpdatePhotoResponseDto> changePhoto(_i25.File? photo) =>
      (super.noSuchMethod(
            Invocation.method(#changePhoto, [photo]),
            returnValue: _i16.Future<_i11.UpdatePhotoResponseDto>.value(
              _FakeUpdatePhotoResponseDto_9(
                this,
                Invocation.method(#changePhoto, [photo]),
              ),
            ),
          )
          as _i16.Future<_i11.UpdatePhotoResponseDto>);

  @override
  _i16.Future<_i12.ChangePasswordResponseDto> changePassword(
    _i27.ChangePasswordRequestBody? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue: _i16.Future<_i12.ChangePasswordResponseDto>.value(
              _FakeChangePasswordResponseDto_10(
                this,
                Invocation.method(#changePassword, [request]),
              ),
            ),
          )
          as _i16.Future<_i12.ChangePasswordResponseDto>);

  @override
  _i16.Future<_i10.UpdateProfileResponseDto> editVehical(
    _i28.UpdateVehicalRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editVehical, [request]),
            returnValue: _i16.Future<_i10.UpdateProfileResponseDto>.value(
              _FakeUpdateProfileResponseDto_8(
                this,
                Invocation.method(#editVehical, [request]),
              ),
            ),
          )
          as _i16.Future<_i10.UpdateProfileResponseDto>);

  @override
  _i16.Future<_i13.AllVehicalResponse> getAllVehicles() =>
      (super.noSuchMethod(
            Invocation.method(#getAllVehicles, []),
            returnValue: _i16.Future<_i13.AllVehicalResponse>.value(
              _FakeAllVehicalResponse_11(
                this,
                Invocation.method(#getAllVehicles, []),
              ),
            ),
          )
          as _i16.Future<_i13.AllVehicalResponse>);
}

/// A class which mocks [SharedPrefHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPrefHelper extends _i1.Mock implements _i29.SharedPrefHelper {
  MockSharedPrefHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.SharedPreferences getPreferenceInstance() =>
      (super.noSuchMethod(
            Invocation.method(#getPreferenceInstance, []),
            returnValue: _FakeSharedPreferences_12(
              this,
              Invocation.method(#getPreferenceInstance, []),
            ),
          )
          as _i14.SharedPreferences);

  @override
  _i16.Future<void> setValue(String? key, dynamic value) =>
      (super.noSuchMethod(
            Invocation.method(#setValue, [key, value]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  dynamic getValue(String? key) =>
      super.noSuchMethod(Invocation.method(#getValue, [key]));

  @override
  _i16.Future<void> removePreference({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#removePreference, [], {#key: key}),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);
}
