// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/features/auth/apply/data/data_source/auth/apply_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:io' as _i19;

import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i5;
import 'package:shared_preferences/shared_preferences.dart' as _i11;
import 'package:tracking_app/core/api_layer/api_client/api_client.dart' as _i12;
import 'package:tracking_app/core/api_layer/models/request/change_password_request_body.dart'
    as _i21;
import 'package:tracking_app/core/api_layer/models/request/update_profile_request_dto.dart'
    as _i20;
import 'package:tracking_app/core/api_layer/models/response/auth/apply_response.dart'
    as _i6;
import 'package:tracking_app/core/api_layer/models/response/profile/change_password_response_dto.dart'
    as _i10;
import 'package:tracking_app/core/api_layer/models/response/profile/get_logged_driver.dart'
    as _i7;
import 'package:tracking_app/core/api_layer/models/response/profile/update_photo_response_dto.dart'
    as _i9;
import 'package:tracking_app/core/api_layer/models/response/profile/update_profile_response_dto.dart'
    as _i8;
import 'package:tracking_app/core/modules/shared_preferences_module.dart'
    as _i22;
import 'package:tracking_app/features/auth/forget_password/data/models/request/forget_password_request_dto.dart'
    as _i14;
import 'package:tracking_app/features/auth/forget_password/data/models/request/reset_password_request_dto.dart'
    as _i16;
import 'package:tracking_app/features/auth/forget_password/data/models/request/verify_reset_code_request_dto.dart'
    as _i15;
import 'package:tracking_app/features/auth/forget_password/data/models/response/forget_password_response_dto.dart'
    as _i2;
import 'package:tracking_app/features/auth/forget_password/data/models/response/reset_password_response_dto.dart'
    as _i4;
import 'package:tracking_app/features/auth/forget_password/data/models/response/verify_reset_code_response_dto.dart'
    as _i3;
import 'package:tracking_app/features/auth/login/data/model/login_request_dto.dart'
    as _i18;
import 'package:tracking_app/features/auth/login/data/model/login_response_dto.dart'
    as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForgetPasswordResponseDto_0 extends _i1.SmartFake
    implements _i2.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyResetCodeResponseDto_1 extends _i1.SmartFake
    implements _i3.VerifyResetCodeResponseDto {
  _FakeVerifyResetCodeResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseDto_2 extends _i1.SmartFake
    implements _i4.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpResponse_3<T> extends _i1.SmartFake
    implements _i5.HttpResponse<T> {
  _FakeHttpResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApplyResponse_4 extends _i1.SmartFake implements _i6.ApplyResponse {
  _FakeApplyResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetLoggedDriver_5 extends _i1.SmartFake
    implements _i7.GetLoggedDriver {
  _FakeGetLoggedDriver_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateProfileResponseDto_6 extends _i1.SmartFake
    implements _i8.UpdateProfileResponseDto {
  _FakeUpdateProfileResponseDto_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdatePhotoResponseDto_7 extends _i1.SmartFake
    implements _i9.UpdatePhotoResponseDto {
  _FakeUpdatePhotoResponseDto_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChangePasswordResponseDto_8 extends _i1.SmartFake
    implements _i10.ChangePasswordResponseDto {
  _FakeChangePasswordResponseDto_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedPreferences_9 extends _i1.SmartFake
    implements _i11.SharedPreferences {
  _FakeSharedPreferences_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i12.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.ForgetPasswordResponseDto> forgetPassword({
    required _i14.ForgetPasswordRequestDto? forgetPasswordRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [], {
              #forgetPasswordRequestDto: forgetPasswordRequestDto,
            }),
            returnValue: _i13.Future<_i2.ForgetPasswordResponseDto>.value(
              _FakeForgetPasswordResponseDto_0(
                this,
                Invocation.method(#forgetPassword, [], {
                  #forgetPasswordRequestDto: forgetPasswordRequestDto,
                }),
              ),
            ),
          )
          as _i13.Future<_i2.ForgetPasswordResponseDto>);

  @override
  _i13.Future<_i3.VerifyResetCodeResponseDto> verifyResetCode({
    required _i15.VerifyResetCodeRequestDto? verifyResetCodeRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [], {
              #verifyResetCodeRequestDto: verifyResetCodeRequestDto,
            }),
            returnValue: _i13.Future<_i3.VerifyResetCodeResponseDto>.value(
              _FakeVerifyResetCodeResponseDto_1(
                this,
                Invocation.method(#verifyResetCode, [], {
                  #verifyResetCodeRequestDto: verifyResetCodeRequestDto,
                }),
              ),
            ),
          )
          as _i13.Future<_i3.VerifyResetCodeResponseDto>);

  @override
  _i13.Future<_i4.ResetPasswordResponseDto> resetPassword({
    required _i16.ResetPasswordRequestDto? resetPasswordRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #resetPasswordRequestDto: resetPasswordRequestDto,
            }),
            returnValue: _i13.Future<_i4.ResetPasswordResponseDto>.value(
              _FakeResetPasswordResponseDto_2(
                this,
                Invocation.method(#resetPassword, [], {
                  #resetPasswordRequestDto: resetPasswordRequestDto,
                }),
              ),
            ),
          )
          as _i13.Future<_i4.ResetPasswordResponseDto>);

  @override
  _i13.Future<_i5.HttpResponse<_i17.LoginResponseDto>> login({
    required _i18.LoginRequestDto? loginRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#loginRequestDto: loginRequestDto}),
            returnValue:
                _i13.Future<_i5.HttpResponse<_i17.LoginResponseDto>>.value(
                  _FakeHttpResponse_3<_i17.LoginResponseDto>(
                    this,
                    Invocation.method(#login, [], {
                      #loginRequestDto: loginRequestDto,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i5.HttpResponse<_i17.LoginResponseDto>>);

  @override
  _i13.Future<_i6.ApplyResponse> apply(
    String? email,
    String? password,
    String? rePassword,
    String? firstName,
    String? lastName,
    String? phone,
    String? gender,
    String? NID,
    String? vehicleType,
    String? vehicleNumber,
    String? country,
    _i19.File? vehicleLicense,
    _i19.File? NIDImg,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#apply, [
              email,
              password,
              rePassword,
              firstName,
              lastName,
              phone,
              gender,
              NID,
              vehicleType,
              vehicleNumber,
              country,
              vehicleLicense,
              NIDImg,
            ]),
            returnValue: _i13.Future<_i6.ApplyResponse>.value(
              _FakeApplyResponse_4(
                this,
                Invocation.method(#apply, [
                  email,
                  password,
                  rePassword,
                  firstName,
                  lastName,
                  phone,
                  gender,
                  NID,
                  vehicleType,
                  vehicleNumber,
                  country,
                  vehicleLicense,
                  NIDImg,
                ]),
              ),
            ),
          )
          as _i13.Future<_i6.ApplyResponse>);

  @override
  _i13.Future<_i7.GetLoggedDriver> getLoggedUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedUserData, []),
            returnValue: _i13.Future<_i7.GetLoggedDriver>.value(
              _FakeGetLoggedDriver_5(
                this,
                Invocation.method(#getLoggedUserData, []),
              ),
            ),
          )
          as _i13.Future<_i7.GetLoggedDriver>);

  @override
  _i13.Future<_i8.UpdateProfileResponseDto> editProfile(
    _i20.UpdateProfileRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [request]),
            returnValue: _i13.Future<_i8.UpdateProfileResponseDto>.value(
              _FakeUpdateProfileResponseDto_6(
                this,
                Invocation.method(#editProfile, [request]),
              ),
            ),
          )
          as _i13.Future<_i8.UpdateProfileResponseDto>);

  @override
  _i13.Future<_i9.UpdatePhotoResponseDto> changePhoto(_i19.File? photo) =>
      (super.noSuchMethod(
            Invocation.method(#changePhoto, [photo]),
            returnValue: _i13.Future<_i9.UpdatePhotoResponseDto>.value(
              _FakeUpdatePhotoResponseDto_7(
                this,
                Invocation.method(#changePhoto, [photo]),
              ),
            ),
          )
          as _i13.Future<_i9.UpdatePhotoResponseDto>);

  @override
  _i13.Future<_i10.ChangePasswordResponseDto> changePassword(
    _i21.ChangePasswordRequestBody? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue: _i13.Future<_i10.ChangePasswordResponseDto>.value(
              _FakeChangePasswordResponseDto_8(
                this,
                Invocation.method(#changePassword, [request]),
              ),
            ),
          )
          as _i13.Future<_i10.ChangePasswordResponseDto>);
}

/// A class which mocks [SharedPrefHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPrefHelper extends _i1.Mock implements _i22.SharedPrefHelper {
  MockSharedPrefHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.SharedPreferences getPreferenceInstance() =>
      (super.noSuchMethod(
            Invocation.method(#getPreferenceInstance, []),
            returnValue: _FakeSharedPreferences_9(
              this,
              Invocation.method(#getPreferenceInstance, []),
            ),
          )
          as _i11.SharedPreferences);

  @override
  _i13.Future<void> setValue(String? key, dynamic value) =>
      (super.noSuchMethod(
            Invocation.method(#setValue, [key, value]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  dynamic getValue(String? key) =>
      super.noSuchMethod(Invocation.method(#getValue, [key]));

  @override
  _i13.Future<void> removePreference({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#removePreference, [], {#key: key}),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}
