// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/features/forget_password/data/datasources/impl/forget_password_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:io' as _i17;

import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i5;
import 'package:tracking_app/core/api_layer/api_client/api_client.dart' as _i10;
import 'package:tracking_app/core/api_layer/models/response/auth/apply_response.dart'
    as _i6;
import 'package:tracking_app/features/auth/forget_password/data/models/request/forget_password_request_dto.dart'
    as _i12;
import 'package:tracking_app/features/auth/forget_password/data/models/request/reset_password_request_dto.dart'
    as _i14;
import 'package:tracking_app/features/auth/forget_password/data/models/request/verify_reset_code_request_dto.dart'
    as _i13;
import 'package:tracking_app/features/auth/forget_password/data/models/response/forget_password_response_dto.dart'
    as _i2;
import 'package:tracking_app/features/auth/forget_password/data/models/response/reset_password_response_dto.dart'
    as _i4;
import 'package:tracking_app/features/auth/forget_password/data/models/response/verify_reset_code_response_dto.dart'
    as _i3;
import 'package:tracking_app/features/auth/forget_password/domain/entities/forget_password_response_entity.dart'
    as _i7;
import 'package:tracking_app/features/auth/forget_password/domain/entities/reset_password_response_entity.dart'
    as _i8;
import 'package:tracking_app/features/auth/forget_password/domain/entities/verify_reset_code_entity.dart'
    as _i9;
import 'package:tracking_app/features/auth/login/data/model/login_request_dto.dart'
    as _i16;
import 'package:tracking_app/features/auth/login/data/model/login_response_dto.dart'
    as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForgetPasswordResponseDto_0 extends _i1.SmartFake
    implements _i2.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyResetCodeResponseDto_1 extends _i1.SmartFake
    implements _i3.VerifyResetCodeResponseDto {
  _FakeVerifyResetCodeResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseDto_2 extends _i1.SmartFake
    implements _i4.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpResponse_3<T> extends _i1.SmartFake
    implements _i5.HttpResponse<T> {
  _FakeHttpResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApplyResponse_4 extends _i1.SmartFake implements _i6.ApplyResponse {
  _FakeApplyResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordResponseEntity_5 extends _i1.SmartFake
    implements _i7.ForgetPasswordResponseEntity {
  _FakeForgetPasswordResponseEntity_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseEntity_6 extends _i1.SmartFake
    implements _i8.ResetPasswordResponseEntity {
  _FakeResetPasswordResponseEntity_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyResetCodeResponseEntity_7 extends _i1.SmartFake
    implements _i9.VerifyResetCodeResponseEntity {
  _FakeVerifyResetCodeResponseEntity_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i10.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i2.ForgetPasswordResponseDto> forgetPassword({
    required _i12.ForgetPasswordRequestDto? forgetPasswordRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [], {
              #forgetPasswordRequestDto: forgetPasswordRequestDto,
            }),
            returnValue: _i11.Future<_i2.ForgetPasswordResponseDto>.value(
              _FakeForgetPasswordResponseDto_0(
                this,
                Invocation.method(#forgetPassword, [], {
                  #forgetPasswordRequestDto: forgetPasswordRequestDto,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.ForgetPasswordResponseDto>);

  @override
  _i11.Future<_i3.VerifyResetCodeResponseDto> verifyResetCode({
    required _i13.VerifyResetCodeRequestDto? verifyResetCodeRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [], {
              #verifyResetCodeRequestDto: verifyResetCodeRequestDto,
            }),
            returnValue: _i11.Future<_i3.VerifyResetCodeResponseDto>.value(
              _FakeVerifyResetCodeResponseDto_1(
                this,
                Invocation.method(#verifyResetCode, [], {
                  #verifyResetCodeRequestDto: verifyResetCodeRequestDto,
                }),
              ),
            ),
          )
          as _i11.Future<_i3.VerifyResetCodeResponseDto>);

  @override
  _i11.Future<_i4.ResetPasswordResponseDto> resetPassword({
    required _i14.ResetPasswordRequestDto? resetPasswordRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #resetPasswordRequestDto: resetPasswordRequestDto,
            }),
            returnValue: _i11.Future<_i4.ResetPasswordResponseDto>.value(
              _FakeResetPasswordResponseDto_2(
                this,
                Invocation.method(#resetPassword, [], {
                  #resetPasswordRequestDto: resetPasswordRequestDto,
                }),
              ),
            ),
          )
          as _i11.Future<_i4.ResetPasswordResponseDto>);

  @override
  _i11.Future<_i5.HttpResponse<_i15.LoginResponseDto>> login({
    required _i16.LoginRequestDto? loginRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#loginRequestDto: loginRequestDto}),
            returnValue:
                _i11.Future<_i5.HttpResponse<_i15.LoginResponseDto>>.value(
                  _FakeHttpResponse_3<_i15.LoginResponseDto>(
                    this,
                    Invocation.method(#login, [], {
                      #loginRequestDto: loginRequestDto,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i5.HttpResponse<_i15.LoginResponseDto>>);

  @override
  _i11.Future<_i6.ApplyResponse> apply(
    String? email,
    String? password,
    String? rePassword,
    String? firstName,
    String? lastName,
    String? phone,
    String? gender,
    String? NID,
    String? vehicleType,
    String? vehicleNumber,
    String? country,
    _i17.File? vehicleLicense,
    _i17.File? NIDImg,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#apply, [
              email,
              password,
              rePassword,
              firstName,
              lastName,
              phone,
              gender,
              NID,
              vehicleType,
              vehicleNumber,
              country,
              vehicleLicense,
              NIDImg,
            ]),
            returnValue: _i11.Future<_i6.ApplyResponse>.value(
              _FakeApplyResponse_4(
                this,
                Invocation.method(#apply, [
                  email,
                  password,
                  rePassword,
                  firstName,
                  lastName,
                  phone,
                  gender,
                  NID,
                  vehicleType,
                  vehicleNumber,
                  country,
                  vehicleLicense,
                  NIDImg,
                ]),
              ),
            ),
          )
          as _i11.Future<_i6.ApplyResponse>);
}

/// A class which mocks [ForgetPasswordResponseDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgetPasswordResponseDto extends _i1.Mock
    implements _i2.ForgetPasswordResponseDto {
  MockForgetPasswordResponseDto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i7.ForgetPasswordResponseEntity toEntity() =>
      (super.noSuchMethod(
            Invocation.method(#toEntity, []),
            returnValue: _FakeForgetPasswordResponseEntity_5(
              this,
              Invocation.method(#toEntity, []),
            ),
          )
          as _i7.ForgetPasswordResponseEntity);
}

/// A class which mocks [ResetPasswordResponseDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordResponseDto extends _i1.Mock
    implements _i4.ResetPasswordResponseDto {
  MockResetPasswordResponseDto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i8.ResetPasswordResponseEntity toEntity() =>
      (super.noSuchMethod(
            Invocation.method(#toEntity, []),
            returnValue: _FakeResetPasswordResponseEntity_6(
              this,
              Invocation.method(#toEntity, []),
            ),
          )
          as _i8.ResetPasswordResponseEntity);
}

/// A class which mocks [VerifyResetCodeResponseDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyResetCodeResponseDto extends _i1.Mock
    implements _i3.VerifyResetCodeResponseDto {
  MockVerifyResetCodeResponseDto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i9.VerifyResetCodeResponseEntity toEntity() =>
      (super.noSuchMethod(
            Invocation.method(#toEntity, []),
            returnValue: _FakeVerifyResetCodeResponseEntity_7(
              this,
              Invocation.method(#toEntity, []),
            ),
          )
          as _i9.VerifyResetCodeResponseEntity);
}
