// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/features/order_details/domain/use_cases/start_order_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tracking_app/core/api_layer/api_result/api_result.dart' as _i4;
import 'package:tracking_app/features/order_details/data/models/request/update_order_request.dart'
    as _i8;
import 'package:tracking_app/features/order_details/domain/entities/start_order_entity.dart'
    as _i5;
import 'package:tracking_app/features/order_details/domain/entities/update_order_state_entity.dart'
    as _i7;
import 'package:tracking_app/features/order_details/domain/repo/start_order_repo.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [OrderDetailsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderDetailsRepo extends _i1.Mock implements _i2.OrderDetailsRepo {
  MockOrderDetailsRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.StartOrderEntity?>> startOrder(
    String? orderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startOrder, [orderId]),
            returnValue: _i3.Future<_i4.ApiResult<_i5.StartOrderEntity?>>.value(
              _i6.dummyValue<_i4.ApiResult<_i5.StartOrderEntity?>>(
                this,
                Invocation.method(#startOrder, [orderId]),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.StartOrderEntity?>>);

  @override
  _i3.Future<_i4.ApiResult<_i7.UpdateOrderStateEntity?>> updateOrder(
    String? orderId,
    _i8.UpdateOrderRequest? updateOrderRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrder, [orderId, updateOrderRequest]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i7.UpdateOrderStateEntity?>>.value(
                  _i6.dummyValue<_i4.ApiResult<_i7.UpdateOrderStateEntity?>>(
                    this,
                    Invocation.method(#updateOrder, [
                      orderId,
                      updateOrderRequest,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i7.UpdateOrderStateEntity?>>);
}
