// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/features/forget_password/data/datasources/impl/forget_password_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tracking_app/core/api_layer/api_client/api_client.dart' as _i8;
import 'package:tracking_app/features/forget_password/data/models/request/forget_password_request_dto.dart'
    as _i10;
import 'package:tracking_app/features/forget_password/data/models/request/reset_password_request_dto.dart'
    as _i12;
import 'package:tracking_app/features/forget_password/data/models/request/verify_reset_code_request_dto.dart'
    as _i11;
import 'package:tracking_app/features/forget_password/data/models/response/forget_password_response_dto.dart'
    as _i2;
import 'package:tracking_app/features/forget_password/data/models/response/reset_password_response_dto.dart'
    as _i4;
import 'package:tracking_app/features/forget_password/data/models/response/verify_reset_code_response_dto.dart'
    as _i3;
import 'package:tracking_app/features/forget_password/domain/entities/forget_password_response_entity.dart'
    as _i5;
import 'package:tracking_app/features/forget_password/domain/entities/reset_password_response_entity.dart'
    as _i6;
import 'package:tracking_app/features/forget_password/domain/entities/verify_reset_code_entity.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForgetPasswordResponseDto_0 extends _i1.SmartFake
    implements _i2.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyResetCodeResponseDto_1 extends _i1.SmartFake
    implements _i3.VerifyResetCodeResponseDto {
  _FakeVerifyResetCodeResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseDto_2 extends _i1.SmartFake
    implements _i4.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordResponseEntity_3 extends _i1.SmartFake
    implements _i5.ForgetPasswordResponseEntity {
  _FakeForgetPasswordResponseEntity_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseEntity_4 extends _i1.SmartFake
    implements _i6.ResetPasswordResponseEntity {
  _FakeResetPasswordResponseEntity_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyResetCodeResponseEntity_5 extends _i1.SmartFake
    implements _i7.VerifyResetCodeResponseEntity {
  _FakeVerifyResetCodeResponseEntity_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i8.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.ForgetPasswordResponseDto> forgetPassword({
    required _i10.ForgetPasswordRequestDto? forgetPasswordRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [], {
              #forgetPasswordRequestDto: forgetPasswordRequestDto,
            }),
            returnValue: _i9.Future<_i2.ForgetPasswordResponseDto>.value(
              _FakeForgetPasswordResponseDto_0(
                this,
                Invocation.method(#forgetPassword, [], {
                  #forgetPasswordRequestDto: forgetPasswordRequestDto,
                }),
              ),
            ),
          )
          as _i9.Future<_i2.ForgetPasswordResponseDto>);

  @override
  _i9.Future<_i3.VerifyResetCodeResponseDto> verifyResetCode({
    required _i11.VerifyResetCodeRequestDto? verifyResetCodeRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [], {
              #verifyResetCodeRequestDto: verifyResetCodeRequestDto,
            }),
            returnValue: _i9.Future<_i3.VerifyResetCodeResponseDto>.value(
              _FakeVerifyResetCodeResponseDto_1(
                this,
                Invocation.method(#verifyResetCode, [], {
                  #verifyResetCodeRequestDto: verifyResetCodeRequestDto,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.VerifyResetCodeResponseDto>);

  @override
  _i9.Future<_i4.ResetPasswordResponseDto> resetPassword({
    required _i12.ResetPasswordRequestDto? resetPasswordRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #resetPasswordRequestDto: resetPasswordRequestDto,
            }),
            returnValue: _i9.Future<_i4.ResetPasswordResponseDto>.value(
              _FakeResetPasswordResponseDto_2(
                this,
                Invocation.method(#resetPassword, [], {
                  #resetPasswordRequestDto: resetPasswordRequestDto,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.ResetPasswordResponseDto>);
}

/// A class which mocks [ForgetPasswordResponseDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgetPasswordResponseDto extends _i1.Mock
    implements _i2.ForgetPasswordResponseDto {
  MockForgetPasswordResponseDto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i5.ForgetPasswordResponseEntity toEntity() =>
      (super.noSuchMethod(
            Invocation.method(#toEntity, []),
            returnValue: _FakeForgetPasswordResponseEntity_3(
              this,
              Invocation.method(#toEntity, []),
            ),
          )
          as _i5.ForgetPasswordResponseEntity);
}

/// A class which mocks [ResetPasswordResponseDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordResponseDto extends _i1.Mock
    implements _i4.ResetPasswordResponseDto {
  MockResetPasswordResponseDto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i6.ResetPasswordResponseEntity toEntity() =>
      (super.noSuchMethod(
            Invocation.method(#toEntity, []),
            returnValue: _FakeResetPasswordResponseEntity_4(
              this,
              Invocation.method(#toEntity, []),
            ),
          )
          as _i6.ResetPasswordResponseEntity);
}

/// A class which mocks [VerifyResetCodeResponseDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyResetCodeResponseDto extends _i1.Mock
    implements _i3.VerifyResetCodeResponseDto {
  MockVerifyResetCodeResponseDto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i7.VerifyResetCodeResponseEntity toEntity() =>
      (super.noSuchMethod(
            Invocation.method(#toEntity, []),
            returnValue: _FakeVerifyResetCodeResponseEntity_5(
              this,
              Invocation.method(#toEntity, []),
            ),
          )
          as _i7.VerifyResetCodeResponseEntity);
}
