name: Dart Linting Action

on:
  pull_request:
    branches: [ main, developement ]
  push:
    branches: [ main, developement ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.35.4

      - name: Install dependencies
        run: flutter pub get
        #

      - name: Run Flutter analyze (lint)
        run: flutter analyze