name: Firebase App Distribution

on:
  push:
    branches:
      - master
      - developement
  pull_request:
    branches:
      - master
      - developement

jobs:
  android-build:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.35.4
          cache: true
          
      - name: Install Flutter dependencies
        run: flutter pub get
        
      - name: Generate files
        run: flutter pub run build_runner build --delete-conflicting-outputs
        
      - name: Build Android Debug APK
        run: flutter build apk --debug
        
      - name: Setup Firebase CLI
        run: npm install -g firebase-tools
        
      - name: Upload Android APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-debug.apk \
            --app ${{ secrets.FIREBASE_APP_ID_ANDROID_DEV }} \
            --groups "Android-team" \
            --release-notes "Android Debug Build - Branch: ${{ github.ref_name }} - Commit: ${{ github.sha }}" \
            --token ${{ secrets.FIREBASE_CI_TOKEN }}