# This workflow runs SonarQube analysis but skips the quality gate check
# This allows the build to continue even if quality gate conditions are not met
name: SonarQube Analysis (Skip Quality Gate)
on:
  push:
    branches:
      - master
      - developement
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      # The analysis requires to retrieve dependencies and build successfully
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.35.4

      - name: Install dependencies
        run: flutter pub get

      - name: Generate files
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Generate LCOV report
        run: |
          # Install lcov if needed (usually available on Ubuntu)
          sudo apt-get update
          sudo apt-get install -y lcov
          # Convert coverage to LCOV format
          genhtml coverage/lcov.info -o coverage/html
      - name: Create SonarQube properties file
        run: |
          echo "sonar.projectKey=tracking_app" >> sonar-project.properties
          echo "sonar.qualitygate.wait=false" >> sonar-project.properties
          echo "sonar.coverage.exclusions=**/*test/**/*,**/*Test.dart,**/test/**/*" >> sonar-project.properties
          echo "sonar.sources=lib/" >> sonar-project.properties
          echo "sonar.tests=test/" >> sonar-project.properties
          echo "sonar.dart.coverage.reportPaths=coverage/lcov.info" >> sonar-project.properties
          echo "sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.mocks.dart" >> sonar-project.properties
      - name: SonarQube Scan (Skip Quality Gate)
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}